# Generated by Django 4.2.2 on 2023-06-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_pessoa_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
